package code

/* This file is automatically generated */

type SlipType byte

func (obj SlipType) Byte() byte {
	return byte(obj)
}

const (
	SlipEnd    SlipType = 192 //0xc0
	SlipEsc    SlipType = 219 //0xdb
	SlipEscEnd SlipType = 220 //0xdc
	SlipEscEsc SlipType = 221 //0xdd
)

const (
	SlipTextEnd    = "End"
	SlipTextEsc    = "Esc"
	SlipTextEscEnd = "Esc End"
	SlipTextEscEsc = "Esc Esc"
)

var SlipMap = map[SlipType]string{
	SlipEnd:    SlipTextEnd,
	SlipEsc:    SlipTextEsc,
	SlipEscEnd: SlipTextEscEnd,
	SlipEscEsc: SlipTextEscEsc,
}

func (obj SlipType) String() string {
	val, ok := SlipMap[obj]
	if ok {
		return val
	}
	return "Unknown SlipType"
}
